name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          override: true
          components: rustfmt
      - name: format-typescript
        run: |
          cd contracts/toCKB-typescript
          cargo fmt --all -- --check
      - name: format-lockscript
        run: |
          cd contracts/toCKB-lockscript
          cargo fmt --all -- --check
      - name: format-tests
        run: |
          cd tests
          cargo fmt --all -- --check
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-capsule
        run: |
          wget -c https://github.com/nervosnetwork/capsule/releases/download/v0.2.3/capsule_v0.2.3_x86_64-linux.tar.gz
          tar -zxvf capsule_v0.2.3_x86_64-linux.tar.gz
      - name: build
        run: ./capsule_v0.2.3_x86_64-linux/capsule build
